name: basic_utils
description: Common util classes providing a solution for different situations.
version: 2.4.5
homepage: https://github.com/Ephenodrom/Dart-Basic-Utils
publish_to: https://pub.dartlang.org
author: Daniel Linsenmeier <daniel@ephenodrom.de>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0
  logging: ^0.11.3+2
  json_annotation: ">=2.0.0 <=3.0.1"
  pointycastle: ^1.0.1
  asn1lib: ^0.5.15
  convert: ^2.1.1
  crypto: ^2.1.3
  intl: ^0.16.0


dev_dependencies:
  build_runner: ^1.5.0
  json_serializable: ^3.2.2
  pedantic: ^1.9.0
  test: ^1.6.0