name: basic_utils
description: Common util classes providing a solution for different situations.
version: 3.9.2
homepage: https://github.com/Ephenodrom/Dart-Basic-Utils
publish_to: https://pub.dartlang.org

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  http: ^0.13.3
  logging: ^1.0.1
  json_annotation: ^4.3.0
  pointycastle: ^3.3.2

dev_dependencies:
  build_runner: ^1.11.5
  json_serializable: ^6.0.1
  pedantic: ^1.10.0
  test: ^1.16.8
  convert: ^3.0.0

false_secrets:
 - /test/crypto_utils_test.dart