name: basic_utils
description: Common util classes for Strings, Dates, X509, PKCS, Cryptographie and more.
version: 5.5.2
homepage: https://github.com/Ephenodrom/Dart-Basic-Utils
#publish_to: https://pub.dartlang.org

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  http: ^0.13.5
  logging: ^1.1.1
  json_annotation: ^4.6.0
  pointycastle: ^3.7.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.0.1
  test: ^1.22.2

false_secrets:
 - /test/crypto_utils_test.dart
 - /test/pkcs12_utils_test.dart
